
import os
import time
import feedparser
from datetime import datetime
from google import genai

# 1. 설정
RSS_URL = "https://cdn.aitimes.com/rss/gn_rss_allArticle.xml"
SAVE_DIR = "research/readings/ai_times_trends"
os.makedirs(SAVE_DIR, exist_ok=True)

api_key = os.environ.get("GEMINI_API_KEY")

def get_ai_wisdom(title, desc):
    """AI Times 기사를 분석하여 Antigravity 프로젝트 적용점 도출 (Gemini 3)"""
    if not api_key:
        return "💡 분석 대기: API Key 설정이 필요합니다."
    
    try:
        client = genai.Client(api_key=api_key)
        prompt = f"""
        당신은 'Antigravity' 프로젝트의 시니어 데이터 분석가입니다. 
        축구 데이터(EPL/K-League) 분석 및 AI 에이전트 개발 관점에서 다음 뉴스를 분석하세요.
        
        [뉴스 제목]: {title}
        [뉴스 요약]: {desc[:600]}
        
        [미션]:
        이 뉴스가 우리의 데이터 파이프라인, 예측 모델(DLinear 등), 또는 사용자 UI/UX에 줄 수 있는 
        '구체적인 영감'이나 '기술적 적용점'을 한 문장으로 도출하세요.
        """
        
        response = client.models.generate_content(
            model='gemini-3-flash-preview',
            contents=prompt
        )
        return response.text.replace('\n', ' ').strip()
    except Exception as e:
        return f"분석 일시 중단... ({str(e)[:50]})"

def analyze_and_report(post):
    print(f"   ↳ 🧠 AI 분석 중... ", end=" ", flush=True)
    wisdom = get_ai_wisdom(post.title, post.summary if hasattr(post, 'summary') else post.description)
    print("✅")
    return f"### {post.title}\n\n**Data Analyst Insight:**\n{wisdom}\n\n**Link**: {post.link}"

def main():
    print("📰 AI Times Knowledge Harvester (Next-Gen Engine)")
    feed = feedparser.parse(RSS_URL)
    
    # 최신 뉴스 8개 분석
    posts = feed.entries[:8]
    today_str = datetime.now().strftime("%Y-%m-%d")
    
    results = []
    for i, post in enumerate(posts):
        print(f"[{i+1}/{len(posts)}] {post.title[:45]}...")
        results.append(analyze_and_report(post))
        time.sleep(0.5) # API 속도 조절
        
    report_path = os.path.join(SAVE_DIR, f"aitimes_digest_{today_str}.md")
    with open(report_path, "w", encoding='utf-8') as f:
        f.write(f"# AI Times Daily Intelligence ({today_str})\n\n" + "\n\n".join(results))
        f.write(f"\n\n---\n*Generated by Antigravity Senior Analyst System (v3.0)*")
        
    print(f"\n✨ AI Times 리포트 생성 완료: {report_path}")

if __name__ == "__main__":
    main()
